version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: yarn install
      - run:
          name: "Build project"
          command: yarn build
      - run:
          name: "Set up npm auth token"
          command: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc
      - run:
          name: "Deploy image to npm"
          command: npm publish

  test:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: yarn install
      - run:
          name: Run eslint
          command: yarn lint
      # - run:
      #     name: Run test
      #     command: yarn test

  test-version:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: Run version test
          command: yarn test:version

workflows:
  version: 2

  build:
    jobs:
      - test
      - test-version:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - test-version
            - test
          filters:
            branches:
              only:
                - master
